
export const individualPlans = [
  {
    title: "Free Trial",
    price: "₹0",
    period: "for 7 days",
    subtitle: "Try essential features",
    description: "Experience Sakha AI for 7 days",
    features: [
      { name: "5 Concept Cards (Auto-generated)", included: true },
      { name: "5 Flashcards", included: true },
      { name: "5 Practice Exams with analytics", included: true },
      { name: "1 Academic Advisor plan", included: true },
      { name: "Basic Smart Study Plan", included: true },
      { name: "10 AI Tutor requests", included: true },
      { name: "Feel Good Corner", included: true },
      { name: "Custom Card Creation", included: false },
      { name: "Surrounding Influence", included: false },
      { name: "Mood-Based Study Plan", included: false },
    ],
    recommended: false,
    color: "gray",
    trial: true
  },
  {
    title: "Pro Plan (Monthly)",
    price: "₹999",
    period: "/month",
    subtitle: "Full learning experience",
    description: "Complete AI-powered learning companion",
    features: [
      { name: "Unlimited Concept Cards (via Study Plan)", included: true },
      { name: "Unlimited Flashcards", included: true },
      { name: "Unlimited Practice Exams", included: true },
      { name: "Custom Cards (via credits)", included: true },
      { name: "2 Academic Advisor plans/month", included: true },
      { name: "Full + Mood-Based Study Plan", included: true },
      { name: "Unlimited AI Tutor (Fair Use)", included: true },
      { name: "Surrounding Influence", included: true },
      { name: "Feel Good Corner", included: true },
      { name: "Study Groups", included: false },
    ],
    recommended: true,
    color: "purple"
  },
  {
    title: "Pro Plan (Annual)",
    price: "₹9,999",
    period: "/year",
    subtitle: "Save ₹2,000 annually",
    description: "All Pro features with annual savings",
    features: [
      { name: "All Pro Plan Monthly features", included: true },
      { name: "₹2,000 savings vs. monthly plan", included: true },
      { name: "Priority support", included: true },
      { name: "Early access to new features", included: true },
      { name: "Unlimited Concept Cards", included: true },
      { name: "Unlimited Flashcards", included: true },
      { name: "Unlimited Practice Exams", included: true },
      { name: "Custom Cards (via credits)", included: true },
      { name: "Full + Mood-Based Study Plan", included: true },
      { name: "Unlimited AI Tutor (Fair Use)", included: true },
    ],
    color: "blue"
  },
];

export const groupPlans = [
  {
    title: "Group Plan (5 Users)",
    price: "₹3,999",
    period: "/month",
    subtitle: "Shared learning experience",
    description: "For study groups & small batches",
    features: [
      { name: "5 Users included (₹799/user extra)", included: true },
      { name: "Unlimited Concept Cards (via Study Plan)", included: true },
      { name: "Unlimited Flashcards", included: true },
      { name: "Unlimited Practice Exams", included: true },
      { name: "Custom Cards (shared credit pool)", included: true },
      { name: "4 Academic Advisor plans/month shared", included: true },
      { name: "Study Groups", included: true },
      { name: "Admin Dashboard", included: true },
      { name: "Batch Manager", included: true },
    ],
    icon: "users",
    color: "green"
  },
  {
    title: "Group Plan (Annual)",
    price: "₹39,999",
    period: "/year",
    subtitle: "Save ₹8,000 annually",
    description: "Best value for study groups",
    features: [
      { name: "All Group Plan Monthly features", included: true },
      { name: "₹8,000 savings vs. monthly plan", included: true },
      { name: "Priority group support", included: true },
      { name: "Enhanced analytics", included: true },
      { name: "Customized onboarding session", included: true },
      { name: "5 Users included (₹799/user extra)", included: true },
      { name: "Batch Manager", included: true },
      { name: "Admin Dashboard", included: true },
    ],
    icon: "building",
    color: "blue",
    recommended: true
  }
];

export const faq = [
  {
    question: "How do free access limits work?",
    answer: "The Free Plan offers limited access to features for 7 days. This includes 5 Concept Cards, 5 Flashcards, 5 Practice Exams, 1 Academic Advisor plan, Basic Smart Study Plan, 10 AI Tutor requests, and access to the Feel Good Corner. These limits are clearly marked when using the features."
  },
  {
    question: "What is the Card Credit system?",
    answer: "Card Credits allow you to create custom Concept Cards or Flashcards beyond what's automatically generated by your Study Plan. We offer credit packs at different price points: 50 Credits (₹99), 100 Credits (₹179), 250 Credits (₹399), and 100 Exam Credits (₹499). Each regular card costs 1 credit while exam cards cost 2 credits due to their more detailed AI generation."
  },
  {
    question: "How do group plans work?",
    answer: "Our Group Plan supports 5 users by default (₹3,999/month) with the ability to add more users at ₹799 per additional user. Group plans include shared features like 4 Academic Advisor plans per month, a shared credit pool for custom cards, and admin tools including Batch Manager to organize your study group."
  },
  {
    question: "What's the difference between monthly and annual plans?",
    answer: "Annual plans offer significant savings: the Pro Plan Annual saves ₹2,000 compared to monthly billing (₹9,999 vs ₹11,988), and the Group Plan Annual saves ₹8,000 (₹39,999 vs ₹47,988). Annual plans also include priority support and early access to new features."
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept all major credit cards, debit cards, UPI, and net banking in India. For Institute and Corporate plans, we also offer invoice-based payments."
  }
];
