
import React from 'react';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const TermsPage = () => {
  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-purple-50/50 via-white to-blue-50/50">
      <Header />
      
      <main className="flex-grow container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold mb-6">Terms & Conditions</h1>
          <p className="text-gray-600 mb-8">Last updated: April 28, 2025</p>
          
          <div className="prose prose-purple max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">1. Introduction</h2>
              <p>
                Welcome to Sakha AI, operated by Greatwisdom India Pvt Ltd ("Company", "we", "our", "us"). By accessing or using our website, mobile application, or any of our services (collectively, the "Services"), you agree to comply with and be bound by these Terms and Conditions. Please read these Terms carefully before using our Services.
              </p>
              <p className="mt-2">
                If you do not agree with these Terms, please do not access or use our Services.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">2. About Our Services</h2>
              <p>
                Sakha AI is an AI-powered educational platform designed to help students prepare for competitive exams through personalized learning experiences. Our platform combines in-house AI models with open-source AI engines to deliver adaptive learning content, personalized tutoring, and study planning.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">3. User Accounts</h2>
              <p>
                When you create an account with us, you must provide accurate and complete information, and keep it updated. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">4. User Conduct</h2>
              <p>
                You agree not to:
              </p>
              <ul className="list-disc pl-6 mt-2">
                <li>Use our Services for any illegal purpose or in violation of any applicable laws</li>
                <li>Attempt to gain unauthorized access to any part of our Services</li>
                <li>Interfere with or disrupt the operation of our Services</li>
                <li>Reproduce, distribute, modify, or create derivative works of our content</li>
                <li>Share your account credentials with others or allow others to access your account</li>
                <li>Use our Services to distribute malware, viruses, or other malicious code</li>
              </ul>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">5. Intellectual Property</h2>
              <p>
                All content, features, and functionality available through our Services, including but not limited to text, graphics, logos, icons, images, audio clips, digital downloads, data compilations, and software, are owned by Greatwisdom India Pvt Ltd, its licensors, or other providers of such material and are protected by copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">6. AI Models & Technology</h2>
              <p>
                Our Services utilize both proprietary in-house AI models and open-source AI engines. The content generated by these AI systems is provided "as is" without any warranties. While we strive for accuracy, we do not guarantee that the AI-generated content will be error-free, complete, or suitable for your specific needs.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">7. Subscription & Payment</h2>
              <p>
                Some features of our Services require a subscription. By subscribing, you agree to pay the fees according to the pricing plan you select. We reserve the right to change our prices with reasonable notice. All payments are non-refundable except as expressly provided in these Terms or required by applicable law.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">8. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, Greatwisdom India Pvt Ltd shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:
              </p>
              <ul className="list-disc pl-6 mt-2">
                <li>Your use of or inability to use our Services</li>
                <li>Any unauthorized access to or use of our servers and/or any personal information stored therein</li>
                <li>Any errors, mistakes, or inaccuracies in our content</li>
                <li>Any interruption or cessation of transmission to or from our Services</li>
              </ul>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">9. Changes to Terms</h2>
              <p>
                We reserve the right to modify these Terms at any time. When we make changes, we will update the "Last Updated" date at the top of this page. Your continued use of our Services after any such changes constitutes your acceptance of the new Terms.
              </p>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold mb-4">10. Contact Information</h2>
              <p>
                If you have any questions about these Terms, please contact us at:
              </p>
              <p className="mt-2">
                Greatwisdom India Pvt Ltd<br/>
                Email: hello@sakhaai.com<br/>
                Address: Nasscom office Udyog Vihar, Gurgaon, India
              </p>
            </section>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default TermsPage;
