
import { StudentProfile, UserRoleEnum, SubscriptionTypeEnum, MoodType } from "@/types/user/base";

export const mockStudentProfile: StudentProfile = {
  id: "s123456",
  name: "Alex Johnson",
  email: "alex.johnson@example.com",
  role: "student",
  avatar: "/lovable-uploads/avatars/student-male-1.svg",
  gender: "male",
  createdAt: "2023-08-15T10:30:00Z",
  updatedAt: "2023-10-20T15:45:00Z",
  lastLogin: "2023-10-20T15:45:00Z",
  currentMood: "motivated",
  moodHistory: [
    { mood: "happy", timestamp: "2023-10-19T10:30:00Z" },
    { mood: "focused", timestamp: "2023-10-18T14:15:00Z" },
    { mood: "tired", timestamp: "2023-10-17T18:45:00Z" },
    { mood: "motivated", timestamp: "2023-10-16T09:30:00Z" },
  ],
  joinDate: "2023-08-15T10:30:00Z",
  personalityType: "visual",
  areasOfInterest: [
    { id: "physics", name: "Physics", level: "advanced" },
    { id: "mathematics", name: "Mathematics", level: "intermediate" },
    { id: "computer-science", name: "Computer Science", level: "beginner" },
  ],
  loginCount: 27,
  completedOnboarding: true,
  bio: "High school student preparing for engineering entrance exams. Love physics and mathematics.",
  phoneNumber: "+1234567890",
  lastActive: "2023-10-20T15:45:00Z",
  subscription: "premium",
  grade: "12",
  subjects: [
    { id: "physics", name: "Physics", progress: 75 },
    { id: "mathematics", name: "Mathematics", progress: 68 },
    { id: "chemistry", name: "Chemistry", progress: 50 },
  ],
  goals: [
    {
      id: "g1",
      title: "IIT-JEE",
      progress: 65,
      description: "Prepare for the Joint Entrance Examination",
      status: "in-progress",
      dueDate: "2024-04-15",
    },
    {
      id: "g2",
      title: "Physics Olympiad",
      progress: 40,
      description: "Prepare for the International Physics Olympiad",
      status: "in-progress",
      dueDate: "2023-12-10",
    },
  ],
  personality: "analytical",
  achievements: [
    { id: "a1", name: "Physics Champion", progress: 100 },
    { id: "a2", name: "Mathematics Wizard", progress: 80 },
  ],
  educationLevel: "High School",
  studyStreak: 15,
  quizzesTaken: 42,
  flashcardsCreated: 120,
  examPreparation: "IIT-JEE",
  studyHoursToday: 5.5,
  subjectsCovered: 3,
  quizPerformance: 82,
  mood: "motivated" as MoodType,
  syllabusCoverage: 68,
  strongSubjects: ["Physics", "Calculus"],
  weakSubjects: ["Organic Chemistry", "Thermodynamics"],
};
