
export const institutes = [
  "IIT Delhi",
  "IIT Bombay",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT BHU Varanasi",
  "IIT Indore",
  "IIT Mandi",
  "AIIMS Delhi",
  "AIIMS Bhubaneswar",
  "AIIMS Bhopal",
  "AIIMS Jodhpur",
  "AIIMS Patna",
  "AIIMS Raipur",
  "AIIMS Rishikesh",
  "NIT Trichy",
  "NIT Warangal",
  "NIT Surathkal",
  "NIT Calicut",
  "Delhi University",
  "Jadavpur University",
  "Anna University",
  "Banaras Hindu University",
  "Aligarh Muslim University",
  "Jamia Millia Islamia",
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "VIT Vellore",
  "VIT Chennai",
  "SRM Chennai",
  "Manipal Institute of Technology",
  "Amity University",
  "Chandigarh University",
  "Lovely Professional University",
  "Jain University",
  "Christ University",
  "DY Patil University",
  "Symbiosis International University",
  "NMIMS Mumbai",
  "Thapar Institute of Engineering and Technology",
  "PES University",
  "RV College of Engineering",
  "BMS College of Engineering",
  "Dayananda Sagar College of Engineering",
  "Shri Ram College of Commerce",
  "St. Stephen's College",
  "Lady Shri Ram College for Women",
  "Loyola College",
  "Christ College",
  "Xavier's College Mumbai",
  "Fergusson College",
  "Presidency College Chennai",
  "Mount Carmel College",
  "Ethiraj College for Women",
  "PSG College of Technology",
  "Coimbatore Institute of Technology",
  "College of Engineering Pune",
  "VJTI Mumbai",
  "IIIT Hyderabad",
  "IIIT Delhi",
  "IIIT Bangalore",
  "ISI Kolkata",
  "ISI Delhi",
  "ISI Bangalore",
  "NIFT Delhi",
  "NIFT Mumbai",
  "NIFT Kolkata",
  "NID Ahmedabad",
  "NID Bangalore",
  "FTII Pune",
  "SRFTI Kolkata",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Lucknow",
  "IIM Indore",
  "IIM Kozhikode",
  "XLRI Jamshedpur",
  "MDI Gurgaon",
  "FMS Delhi",
  "JIPMER Puducherry",
  "CMC Vellore",
  "AFMC Pune",
  "Maulana Azad Medical College",
  "Kasturba Medical College",
  "St. John's Medical College",
  "National Law School of India University",
  "NALSAR University of Law",
  "WB National University of Juridical Sciences",
  "IISc Bangalore",
  "Homi Bhabha National Institute",
  "TIFR Mumbai",
  "Other"
];
