
import React from "react";
import { useNavigate } from "react-router-dom";
import AdminLayout from "@/components/admin/AdminLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  BookOpen, 
  Code, 
  FileText, 
  Github, 
  Globe, 
  HelpCircle, 
  Search, 
  Terminal, 
  Video,
  Download,
  ArrowRight
} from "lucide-react";
import { Input } from "@/components/ui/input";

const DocumentationPage = () => {
  const navigate = useNavigate();
  
  return (
    <AdminLayout>
      <div className="mb-6">
        <h1 className="text-3xl font-bold">System Documentation</h1>
        <p className="text-gray-500">Comprehensive guides and documentation for Sakha AI administration</p>
      </div>
      
      <div className="mb-6">
        <div className="relative">
          <Search className="absolute top-3 left-3 h-5 w-5 text-gray-400" />
          <Input 
            className="pl-10 w-full lg:w-1/2" 
            placeholder="Search documentation..."
          />
        </div>
      </div>
      
      <Tabs defaultValue="guides" className="space-y-6">
        <TabsList className="grid grid-cols-2 sm:grid-cols-4 gap-2">
          <TabsTrigger value="guides">Admin Guides</TabsTrigger>
          <TabsTrigger value="technical">Technical Docs</TabsTrigger>
          <TabsTrigger value="api">API Reference</TabsTrigger>
          <TabsTrigger value="videos">Video Tutorials</TabsTrigger>
        </TabsList>
        
        <TabsContent value="guides">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <BookOpen className="h-5 w-5 text-indigo-500" />
                    <span>Getting Started</span>
                  </div>
                  <Badge className="bg-green-100 text-green-800">Recommended</Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  {[
                    "Admin Dashboard Overview", 
                    "User Management Guide", 
                    "Content Management Basics", 
                    "AI Personalization Settings",
                    "System Monitoring Guide"
                  ].map((title, idx) => (
                    <div key={idx} className="flex items-center justify-between border-b pb-2">
                      <span className="font-medium">{title}</span>
                      <Button variant="ghost" size="sm">Read</Button>
                    </div>
                  ))}
                </div>
                <Button variant="outline" className="w-full">View All Getting Started Guides</Button>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <HelpCircle className="h-5 w-5 text-amber-500" />
                    <span>Frequently Asked Questions</span>
                  </div>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  {[
                    "How do I reset a student's password?", 
                    "How do I approve content generated by AI?", 
                    "How do I update the AI models?", 
                    "How do I export student data?",
                    "How do I customize the learning styles detection?"
                  ].map((title, idx) => (
                    <div key={idx} className="flex items-center justify-between border-b pb-2">
                      <span className="font-medium">{title}</span>
                      <Button variant="ghost" size="sm">Answer</Button>
                    </div>
                  ))}
                </div>
                <Button variant="outline" className="w-full">View All FAQs</Button>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <FileText className="h-5 w-5 text-blue-500" />
                    <span>Administrative Procedures</span>
                  </div>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {[
                    "Student Onboarding Process",
                    "Content Review Guidelines", 
                    "User Support Procedures", 
                    "System Backup & Recovery",
                    "Database Management Protocols"
                  ].map((title, idx) => (
                    <div key={idx} className="flex items-center justify-between border-b pb-2">
                      <span className="font-medium">{title}</span>
                      <Button variant="ghost" size="sm">View</Button>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Globe className="h-5 w-5 text-green-500" />
                    <span>Best Practices</span>
                  </div>
                  <Badge className="bg-blue-100 text-blue-800">Updated</Badge>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {[
                    "Optimizing AI Personalization",
                    "Effective Content Review Strategies", 
                    "User Engagement Maximization", 
                    "Data Privacy Compliance",
                    "System Performance Optimization"
                  ].map((title, idx) => (
                    <div key={idx} className="flex items-center justify-between border-b pb-2">
                      <span className="font-medium">{title}</span>
                      <Button variant="ghost" size="sm">Read</Button>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
        
        <TabsContent value="technical">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Code className="h-5 w-5 text-purple-500" />
                    <span>Technical Documentation</span>
                  </div>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {[
                    "System Architecture Overview",
                    "Database Schema Documentation", 
                    "AI Model Integration Guide", 
                    "API Integration Reference",
                    "Authentication & Authorization"
                  ].map((title, idx) => (
                    <div key={idx} className="flex items-center justify-between border-b pb-2">
                      <span className="font-medium">{title}</span>
                      <Button variant="ghost" size="sm">View</Button>
                    </div>
                  ))}
                </div>
                <Button 
                  variant="default" 
                  className="w-full mt-4 flex items-center justify-center gap-2"
                  onClick={() => navigate('/admin/settings')}
                >
                  <Download size={16} />
                  <span>Download Database Schema</span>
                </Button>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Github className="h-5 w-5 text-gray-800 dark:text-gray-200" />
                    <span>Codebase & Development</span>
                  </div>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {[
                    "Codebase Structure",
                    "Backend Development Guide", 
                    "Frontend Component Library", 
                    "Custom AI Model Development",
                    "Testing & Quality Assurance"
                  ].map((title, idx) => (
                    <div key={idx} className="flex items-center justify-between border-b pb-2">
                      <span className="font-medium">{title}</span>
                      <Button variant="ghost" size="sm">View</Button>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
            
            <Card className="md:col-span-2">
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Terminal className="h-5 w-5 text-red-500" />
                    <span>Flask API Documentation</span>
                  </div>
                  <Badge className="bg-amber-100 text-amber-800">Advanced</Badge>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div>
                    <h3 className="text-lg font-medium mb-3">AI Services</h3>
                    <div className="space-y-2">
                      {[
                        "Learning Style Detection API",
                        "Content Generation API", 
                        "Study Plan Generator API", 
                        "Adaptive Difficulty API",
                        "Emotional Intelligence API"
                      ].map((title, idx) => (
                        <div key={idx} className="flex items-center justify-between border-b pb-2">
                          <span className="text-sm">{title}</span>
                          <Button variant="ghost" size="sm">Docs</Button>
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium mb-3">Data Services</h3>
                    <div className="space-y-2">
                      {[
                        "User Management API",
                        "Content Management API", 
                        "Analytics & Reporting API", 
                        "Notification Services API",
                        "Student Progress API"
                      ].map((title, idx) => (
                        <div key={idx} className="flex items-center justify-between border-b pb-2">
                          <span className="text-sm">{title}</span>
                          <Button variant="ghost" size="sm">Docs</Button>
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium mb-3">System Services</h3>
                    <div className="space-y-2">
                      {[
                        "Authentication API",
                        "System Monitoring API", 
                        "Configuration API", 
                        "File Storage API",
                        "Backup & Recovery API"
                      ].map((title, idx) => (
                        <div key={idx} className="flex items-center justify-between border-b pb-2">
                          <span className="text-sm">{title}</span>
                          <Button variant="ghost" size="sm">Docs</Button>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
                
                <div className="flex justify-center mt-6">
                  <Button>View Complete API Documentation</Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
        
        <TabsContent value="api">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Code className="h-5 w-5 text-indigo-500" />
                <span>API Reference</span>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="relative">
                  <Search className="absolute top-3 left-3 h-4 w-4 text-gray-400" />
                  <Input 
                    className="pl-10" 
                    placeholder="Search API endpoints..."
                  />
                </div>
                
                <div className="border rounded-md">
                  <div className="bg-gray-50 dark:bg-gray-800 p-3 border-b">
                    <div className="flex items-center justify-between">
                      <h3 className="font-medium">API Endpoints</h3>
                      <div className="flex items-center gap-2">
                        <Button variant="outline" size="sm">Authentication</Button>
                        <Button variant="outline" size="sm">Parameters</Button>
                        <Button variant="outline" size="sm">Response Codes</Button>
                      </div>
                    </div>
                  </div>
                  
                  <div className="divide-y">
                    {[
                      { 
                        method: "GET", 
                        endpoint: "/api/students", 
                        description: "Fetch all students with pagination",
                        group: "User Management"
                      },
                      { 
                        method: "POST", 
                        endpoint: "/api/students", 
                        description: "Create a new student account",
                        group: "User Management"
                      },
                      { 
                        method: "GET", 
                        endpoint: "/api/content/concepts", 
                        description: "Retrieve concept cards with filters",
                        group: "Content Management"
                      },
                      { 
                        method: "POST", 
                        endpoint: "/api/ai/generate-content", 
                        description: "Generate content using AI models",
                        group: "AI Services"
                      },
                      { 
                        method: "GET", 
                        endpoint: "/api/analytics/engagement", 
                        description: "Get student engagement metrics",
                        group: "Analytics"
                      },
                      { 
                        method: "POST", 
                        endpoint: "/api/notifications/send", 
                        description: "Send notifications to users",
                        group: "Notification Services"
                      },
                      { 
                        method: "GET", 
                        endpoint: "/api/system/status", 
                        description: "Check system operational status",
                        group: "System Services"
                      },
                      { 
                        method: "GET", 
                        endpoint: "/api/ai/models", 
                        description: "List all available AI models",
                        group: "AI Services"
                      }
                    ].map((api, idx) => (
                      <div key={idx} className="p-3 hover:bg-gray-50 dark:hover:bg-gray-800/50">
                        <div className="flex items-center justify-between">
                          <div>
                            <div className="flex items-center gap-2">
                              <Badge className={
                                api.method === "GET" ? "bg-blue-100 text-blue-800" :
                                api.method === "POST" ? "bg-green-100 text-green-800" :
                                api.method === "PUT" ? "bg-amber-100 text-amber-800" :
                                "bg-red-100 text-red-800"
                              }>
                                {api.method}
                              </Badge>
                              <span className="font-mono text-sm">{api.endpoint}</span>
                            </div>
                            <div className="mt-1 flex items-center gap-2">
                              <span className="text-xs text-gray-500">{api.group}</span>
                              <span className="text-xs text-gray-500">•</span>
                              <span className="text-xs">{api.description}</span>
                            </div>
                          </div>
                          <Button variant="ghost" size="sm">
                            Details
                            <ArrowRight size={14} className="ml-1" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
                
                <div className="flex justify-end">
                  <Button variant="outline">View Full API Documentation</Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="videos">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                title: "Admin Dashboard Tour",
                duration: "10:23",
                category: "Getting Started",
                thumbnail: "dashboard_tour.jpg"
              },
              {
                title: "AI Personalization Settings",
                duration: "15:45",
                category: "Advanced",
                thumbnail: "ai_personalization.jpg"
              },
              {
                title: "Content Management Workflow",
                duration: "12:30",
                category: "Content",
                thumbnail: "content_management.jpg"
              },
              {
                title: "User Management Guide",
                duration: "8:15",
                category: "Administration",
                thumbnail: "user_management.jpg"
              },
              {
                title: "System Monitoring & Alerts",
                duration: "14:50",
                category: "Technical",
                thumbnail: "system_monitoring.jpg"
              },
              {
                title: "AI Model Integration Guide",
                duration: "20:05",
                category: "Advanced",
                thumbnail: "ai_integration.jpg"
              }
            ].map((video, idx) => (
              <Card key={idx} className="overflow-hidden">
                <div className="aspect-video bg-gray-100 dark:bg-gray-800 relative">
                  <div className="absolute inset-0 flex items-center justify-center">
                    <Video className="h-12 w-12 text-gray-400" />
                  </div>
                  <div className="absolute bottom-2 right-2 bg-black/70 text-white text-xs py-0.5 px-2 rounded">
                    {video.duration}
                  </div>
                </div>
                <CardContent className="pt-4">
                  <h3 className="font-medium mb-1">{video.title}</h3>
                  <Badge className="bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300">
                    {video.category}
                  </Badge>
                  <Button variant="ghost" size="sm" className="mt-2 w-full">
                    Watch Tutorial
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>
      </Tabs>
    </AdminLayout>
  );
};

export default DocumentationPage;
